/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Distribuidora;

import Autor.BuscarAutor;
import Conexion.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class BuscarDistribuidora extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarDistribuidora
     */
    public BuscarDistribuidora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mipanel = new javax.swing.JPanel();
        txtRut = new javax.swing.JTextField();
        btnBuscarDis = new javax.swing.JButton();
        lblRut = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblAñosdeVenta = new javax.swing.JLabel();
        lblnumero = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblcomuna = new javax.swing.JLabel();
        lblpais = new javax.swing.JLabel();
        lblfono = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        btnBuscarDis.setText("Buscar");
        btnBuscarDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDisActionPerformed(evt);
            }
        });

        lblRut.setText("Rut");

        lblNombre.setText("Nombre :");

        lblAñosdeVenta.setText("Años de Venta :");

        lblnumero.setText("Numero :");

        lblDireccion.setText("Calle :");

        lblcomuna.setText("Comuna :");

        lblpais.setText("Pais :");

        lblfono.setText("Fono :");

        javax.swing.GroupLayout MipanelLayout = new javax.swing.GroupLayout(Mipanel);
        Mipanel.setLayout(MipanelLayout);
        MipanelLayout.setHorizontalGroup(
            MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MipanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MipanelLayout.createSequentialGroup()
                        .addComponent(lblDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(MipanelLayout.createSequentialGroup()
                        .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MipanelLayout.createSequentialGroup()
                                .addComponent(lblRut)
                                .addGap(58, 58, 58)
                                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscarDis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtRut, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)))
                            .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(60, 60, 60))
                    .addGroup(MipanelLayout.createSequentialGroup()
                        .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblcomuna, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblfono, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(MipanelLayout.createSequentialGroup()
                        .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblAñosdeVenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                            .addComponent(lblnumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        MipanelLayout.setVerticalGroup(
            MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MipanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRut)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarDis)
                .addGap(42, 42, 42)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDireccion)
                .addGap(18, 18, 18)
                .addComponent(lblnumero)
                .addGap(18, 18, 18)
                .addComponent(lblcomuna)
                .addGap(18, 18, 18)
                .addComponent(lblpais)
                .addGap(18, 18, 18)
                .addComponent(lblfono)
                .addGap(18, 18, 18)
                .addComponent(lblAñosdeVenta)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mipanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mipanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDisActionPerformed
        try {                                          
            Conexion ObjetoConexion = new Conexion();
            
            String rut = txtRut.getText();
            if (rut.trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Complete el espacio en blanco"); 
            }
            
            String query = "Select * from rut_dis where rut = '"+rut+"'";
            
            state = ObjetoConexion.getCon().createStatement();
            
            res = state.executeQuery(query);
            
            if (res.next()) {
                lblNombre.setText("Nombre:" + res.getString("nombre"));
                lblDireccion.setText("Calle :" + res.getString("calle"));
                lblnumero.setText("Numero :" + res.getString("numero"));
                lblcomuna.setText("Comuna :" + res.getString("comuna"));
                lblpais.setText("Pais :" + res.getString("pais"));
                lblfono.setText("Fono :" + res.getString("fono"));
                lblAñosdeVenta.setText("Años de Venta :" + res.getString("año_contrato"));
                
            }
            else{
                JOptionPane.showMessageDialog(this, "No hay Registro");
                txtRut.setText("");
                lblNombre.setText("Nombre :");
                lblDireccion.setText("Direccion :");
                lblnumero.setText("Numero :");
                lblcomuna.setText("Comuna :");
                lblpais.setText("Pais :");
                lblfono.setText("Fono :");
                lblAñosdeVenta.setText("Años de Venta :");

            }
        }
        catch (SQLException ex) {
            Logger.getLogger(BuscarDistribuidora.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarDisActionPerformed

    ResultSet res;
    Statement state;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Mipanel;
    private javax.swing.JButton btnBuscarDis;
    private javax.swing.JLabel lblAñosdeVenta;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblcomuna;
    private javax.swing.JLabel lblfono;
    private javax.swing.JLabel lblnumero;
    private javax.swing.JLabel lblpais;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables
}
