/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Distribuidora;

import Autor.CrearAutor;
import Conexion.Conexion;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class CrearDistribuidora extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistrarDistribuidora
     */
    public CrearDistribuidora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mipanel = new javax.swing.JPanel();
        lblRut = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblAñosdeVenta = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtcalle = new javax.swing.JTextField();
        txtnumero = new javax.swing.JTextField();
        txtAños = new javax.swing.JTextField();
        btnCrearDis = new javax.swing.JButton();
        lblcomuna = new javax.swing.JLabel();
        lblpais = new javax.swing.JLabel();
        lblfono = new javax.swing.JLabel();
        txtcomuna = new javax.swing.JTextField();
        txtpais = new javax.swing.JTextField();
        txtfono = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lblRut.setText("Rut");

        lblNombre.setText("Nombre");

        lblDireccion.setText("Calle");

        lblTelefono.setText("Numero");

        lblAñosdeVenta.setText("Años de Venta");

        btnCrearDis.setText("Crear");
        btnCrearDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearDisActionPerformed(evt);
            }
        });

        lblcomuna.setText("Comuna");

        lblpais.setText("Pais");

        lblfono.setText("Fono");

        javax.swing.GroupLayout MipanelLayout = new javax.swing.GroupLayout(Mipanel);
        Mipanel.setLayout(MipanelLayout);
        MipanelLayout.setHorizontalGroup(
            MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MipanelLayout.createSequentialGroup()
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MipanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAñosdeVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(MipanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefono)
                            .addComponent(lblRut)
                            .addComponent(lblNombre)
                            .addComponent(lblDireccion)
                            .addComponent(lblcomuna)
                            .addComponent(lblpais)
                            .addComponent(lblfono))
                        .addGap(58, 58, 58)))
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRut)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(txtcalle, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(txtnumero, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(txtAños, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(btnCrearDis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtcomuna)
                    .addComponent(txtpais)
                    .addComponent(txtfono))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        MipanelLayout.setVerticalGroup(
            MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MipanelLayout.createSequentialGroup()
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MipanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MipanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRut)))
                .addGap(18, 18, 18)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGap(18, 18, 18)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDireccion))
                .addGap(18, 18, 18)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcomuna)
                    .addComponent(txtcomuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpais)
                    .addComponent(txtpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfono)
                    .addComponent(txtfono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAñosdeVenta))
                .addGap(28, 28, 28)
                .addComponent(btnCrearDis)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mipanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mipanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearDisActionPerformed
    try {                                             
            
            Conexion ObjetoConexion = new Conexion();
            
            String rut = txtRut.getText();
            String nombre = txtNombre.getText();
            String direccion = txtcalle.getText();
            String numero = txtnumero.getText();
            String comuna = txtcomuna.getText();
            String pais = txtpais.getText();
            String fono = txtfono.getText();
            String años = txtAños.getText();
            
            int Años = 0;

                 
            if (rut.trim().equals("")||nombre.trim().equals("")|| direccion.trim().equals("")||
                    numero.trim().equals("")||comuna.trim().equals("")||pais.trim().equals("")||
                    fono.trim().equals("")||años.trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Complete los espacios en blanco");
            }
        try{
            Años=Integer.parseInt(años);
            

            String query = " insert into rut_dis values ('"+rut+"','"+nombre+"','"+direccion+"',"
                    + "'"+numero+"','"+comuna+"','"+pais+"','"+fono+"','"+años+"')";

            state = ObjetoConexion.getCon().createStatement();

            try{
            int x = state.executeUpdate(query);

            if (x > 0) {
                JOptionPane.showMessageDialog(this, "Registrado Correctamente");
            }
            else{
                JOptionPane.showMessageDialog(this, "No se pudo Registrar");
              }
            }
            catch(SQLException error){
                JOptionPane.showMessageDialog(this, "Rut ya registrado");
            }

            }
        catch(NumberFormatException error){
        }


        } catch (SQLException ex) {
        Logger.getLogger(CrearAutor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCrearDisActionPerformed

    Statement state;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Mipanel;
    private javax.swing.JButton btnCrearDis;
    private javax.swing.JLabel lblAñosdeVenta;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblcomuna;
    private javax.swing.JLabel lblfono;
    private javax.swing.JLabel lblpais;
    private javax.swing.JTextField txtAños;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtcalle;
    private javax.swing.JTextField txtcomuna;
    private javax.swing.JTextField txtfono;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtpais;
    // End of variables declaration//GEN-END:variables
}
