/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Distribuidora;

import Autor.ModificarAutor;
import Conexion.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class ModificarDistribuidora extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModificarDistribuidora
     */
    public ModificarDistribuidora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        Mipanel = new javax.swing.JPanel();
        lblRut = new javax.swing.JLabel();
        txtrut = new javax.swing.JTextField();
        btnBuscarDis = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtcalle = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtnumero = new javax.swing.JTextField();
        txtaños = new javax.swing.JTextField();
        lblAñosdeVenta = new javax.swing.JLabel();
        btnModificarDis = new javax.swing.JButton();
        txtcomuna = new javax.swing.JTextField();
        lblfono = new javax.swing.JLabel();
        lblcomuna = new javax.swing.JLabel();
        txtpais = new javax.swing.JTextField();
        lblpais = new javax.swing.JLabel();
        txtfono = new javax.swing.JTextField();

        jScrollPane1.setViewportView(jTextPane1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lblRut.setText("Rut");

        btnBuscarDis.setText("Buscar");
        btnBuscarDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDisActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre");

        lblDireccion.setText("Calle");

        lblTelefono.setText("Numero");

        lblAñosdeVenta.setText("Años de Venta");

        btnModificarDis.setText("Modificar");
        btnModificarDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDisActionPerformed(evt);
            }
        });

        lblfono.setText("Fono");

        lblcomuna.setText("Comuna");

        lblpais.setText("Pais");

        javax.swing.GroupLayout MipanelLayout = new javax.swing.GroupLayout(Mipanel);
        Mipanel.setLayout(MipanelLayout);
        MipanelLayout.setHorizontalGroup(
            MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MipanelLayout.createSequentialGroup()
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MipanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblRut)
                        .addGap(58, 58, 58)
                        .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarDis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtrut)))
                    .addGroup(MipanelLayout.createSequentialGroup()
                        .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MipanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTelefono)
                                    .addGroup(MipanelLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(lblNombre)))
                                .addGap(58, 58, 58))
                            .addGroup(MipanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblDireccion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtaños, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtcomuna)
                                .addComponent(txtnombre)
                                .addComponent(txtcalle)
                                .addComponent(txtnumero)
                                .addComponent(txtpais)
                                .addComponent(txtfono, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(59, 59, 59))
            .addGroup(MipanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MipanelLayout.createSequentialGroup()
                        .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcomuna)
                            .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblfono)
                                .addComponent(lblpais)))
                        .addGap(61, 61, 61)
                        .addComponent(btnModificarDis, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(MipanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblAñosdeVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(274, 274, 274))))
        );
        MipanelLayout.setVerticalGroup(
            MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MipanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MipanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRut)))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarDis)
                .addGap(30, 30, 30)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGap(18, 18, 18)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDireccion))
                .addGap(18, 18, 18)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcomuna)
                    .addComponent(txtcomuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpais)
                    .addComponent(txtpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfono)
                    .addComponent(txtfono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtaños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAñosdeVenta))
                .addGap(28, 28, 28)
                .addComponent(btnModificarDis)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mipanel, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mipanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDisActionPerformed
        try {                                          
            Conexion ObjetoConexion = new Conexion();
            
            String rut = txtrut.getText();
            String nombre = txtnombre.getText();
            String calle = txtcalle.getText();
            String numero = txtnumero.getText();
            String comuna = txtcomuna.getText();
            String pais = txtpais.getText();
            String fono = txtfono.getText();
            String años = txtaños.getText();


            String query ="update rut_dis set nombre='"+nombre+"',"
                    + "calle='"+calle+"',numero='"+numero+"',comuna='"+comuna+"',"
                    + "pais='"+pais+"',fono='"+fono+"',año_contrato='"+años+"' where rut = '"+rut+"'";
            
            state = ObjetoConexion.getCon().createStatement();
            int x = state.executeUpdate(query);
            
            if (x > 0) {
                JOptionPane.showMessageDialog(this, "Actualizado");
            }
            else{
                JOptionPane.showMessageDialog(this, "No se pudo Actualizar");
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(ModificarDistribuidora.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModificarDisActionPerformed

    private void btnBuscarDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDisActionPerformed
        try {                                          
            Conexion ObjetoConexion = new Conexion();
            
            String rut = txtrut.getText();
            
            if (rut.trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Complete los espacios en blanco");
            }
            
            String query = "select * from rut_dis where rut ='"+rut+"'";
            
            state = ObjetoConexion.getCon().createStatement();
            
            res = state.executeQuery(query);
            
            if (res.next()) {
                txtnombre.setText(res.getString("nombre"));
                txtcalle.setText(res.getString("calle"));
                txtnumero.setText(res.getString("numero"));
                txtcomuna.setText(res.getString("comuna"));
                txtpais.setText(res.getString("pais"));
                txtfono.setText(res.getString("fono"));
                txtaños.setText(res.getString("año_contrato"));

            }
            else{
                JOptionPane.showMessageDialog(this, "No hay registros");

                txtrut.setText("");
                txtnombre.setText("");
                txtcalle.setText("");
                txtnumero.setText("");
                txtcomuna.setText("");
                txtpais.setText("");
                txtfono.setText("");
                txtaños.setText("");
                
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(ModificarDistribuidora.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarDisActionPerformed

    ResultSet res;
    Statement state;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Mipanel;
    private javax.swing.JButton btnBuscarDis;
    private javax.swing.JButton btnModificarDis;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblAñosdeVenta;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblcomuna;
    private javax.swing.JLabel lblfono;
    private javax.swing.JLabel lblpais;
    private javax.swing.JTextField txtaños;
    private javax.swing.JTextField txtcalle;
    private javax.swing.JTextField txtcomuna;
    private javax.swing.JTextField txtfono;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtpais;
    private javax.swing.JTextField txtrut;
    // End of variables declaration//GEN-END:variables
}
