/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import Autor.BuscarAutor;
import Autor.EliminarAutor;
import Autor.ModificarAutor;
import Autor.CrearAutor;
import Autor.MostraAutores;
import Boleta.BuscarBoleta;
import Boleta.CrearBoleta;
import Boleta.EliminarBoleta;
import Boleta.ModificarBoleta;
import Categoria.BuscarCategoria;
import Categoria.CrearCategoria;
import Categoria.EliminarCategoria;
import Categoria.ModificarCategoria;
import Categoria.MostrarCategorias;
import Cliente.BuscarCliente;
import Cliente.CrearCliente;
import Cliente.EliminarCliente;
import Cliente.ModificarCliente;
import Distribuidora.BuscarDistribuidora;
import Distribuidora.CrearDistribuidora;
import Distribuidora.EliminarDistribuidora;
import Distribuidora.ModificarDistribuidora;
import Distribuidora.MostrarDistribuidores;
import Editorial.BuscarEditorial;
import Editorial.CrearEditorial;
import Editorial.EliminarEditorial;
import Editorial.ModificarEditorial;
import Editorial.MostrarEditorial;
import Factura.BuscarFactura;
import Factura.CrearFactura;
import Factura.EliminarFactura;
import Factura.ModificarFactura;
import Libro.BuscarLibro;
import Libro.CrearLibro;
import Libro.EliminarLibro;
import Libro.ModificarLibro;
import Libro.Mostrartodolibros;
import Metododepago.CrearMetododepago;
import Metododepago.EliminarMetododepago;
import Metododepago.ModificarMetododepago;
import Metododepago.MostrarMetodosdepago;
import Trabajador.BuscarTrabajador;
import Trabajador.CrearTrabajador;
import Trabajador.EliminarTrabajador;
import Trabajador.ModificarTrabajador;
import Transaccion.AnularComprar;
import Transaccion.BuscarComprar;
import Transaccion.CrearCompra;
import Transaccion.ModificarComprar;
import estado.BuscarDescripcion;
import estado.CrearDescripcion;
import estado.EliminarDescripcion;
import estado.ModificarDescripcion;
import estado.MostrarDescripcion;

/**
 *
 * @author Administrador
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        Mipanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        itemCrearDi = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        itemModficarDi = new javax.swing.JMenuItem();
        itemBuscarDi = new javax.swing.JMenuItem();
        itemEliminarDI = new javax.swing.JMenuItem();
        itemmostrartodos = new javax.swing.JMenuItem();
        Menulibro1 = new javax.swing.JMenu();
        Menulibro2 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Menulibro3 = new javax.swing.JMenu();
        Menuautor2 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        itemBuscarAu = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        itemCrearEdi = new javax.swing.JMenuItem();
        itemModificarEdi = new javax.swing.JMenuItem();
        itemBuscarEdi = new javax.swing.JMenuItem();
        itemEliminarEdi = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        Menuautor3 = new javax.swing.JMenu();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        itemBuscarAu1 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        Menuautor4 = new javax.swing.JMenu();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenuItem42 = new javax.swing.JMenuItem();
        itemBuscarAu2 = new javax.swing.JMenuItem();
        jMenuItem43 = new javax.swing.JMenuItem();
        jMenuItem44 = new javax.swing.JMenuItem();
        Menufactura = new javax.swing.JMenu();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        itemtracrear2 = new javax.swing.JMenu();
        itemCrearTra1 = new javax.swing.JMenuItem();
        itemModificarTra1 = new javax.swing.JMenuItem();
        itemBuscarTra1 = new javax.swing.JMenuItem();
        itemEliminarTra1 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        itemCrearCli1 = new javax.swing.JMenuItem();
        itemCrearCli3 = new javax.swing.JMenuItem();
        itemCrearCli4 = new javax.swing.JMenuItem();
        metodopago = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        itemCrearCli = new javax.swing.JMenuItem();
        itemModificarCli = new javax.swing.JMenuItem();
        itemBuscarCli = new javax.swing.JMenuItem();
        itemEliminarCli = new javax.swing.JMenuItem();
        itemtracrear1 = new javax.swing.JMenu();
        itemCrearTra = new javax.swing.JMenuItem();
        itemModificarTra = new javax.swing.JMenuItem();
        itemBuscarTra = new javax.swing.JMenuItem();
        itemEliminarTra = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("File");
        jMenuBar4.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("jMenu8");

        jMenuItem7.setText("jMenuItem7");

        jMenu15.setText("File");
        jMenuBar5.add(jMenu15);

        jMenu16.setText("Edit");
        jMenuBar5.add(jMenu16);

        jMenuItem8.setText("jMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout MipanelLayout = new javax.swing.GroupLayout(Mipanel);
        Mipanel.setLayout(MipanelLayout);
        MipanelLayout.setHorizontalGroup(
            MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        MipanelLayout.setVerticalGroup(
            MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        itemCrearDi.setText("Distribuidores");
        itemCrearDi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCrearDiActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Crear");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        itemCrearDi.add(jMenuItem3);

        itemModficarDi.setText("Modificar");
        itemModficarDi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemModficarDiActionPerformed(evt);
            }
        });
        itemCrearDi.add(itemModficarDi);

        itemBuscarDi.setText("Buscar");
        itemBuscarDi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarDiActionPerformed(evt);
            }
        });
        itemCrearDi.add(itemBuscarDi);

        itemEliminarDI.setText("Eliminar");
        itemEliminarDI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarDIActionPerformed(evt);
            }
        });
        itemCrearDi.add(itemEliminarDI);

        itemmostrartodos.setText("Mostrar todos");
        itemmostrartodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemmostrartodosActionPerformed(evt);
            }
        });
        itemCrearDi.add(itemmostrartodos);

        jMenuBar1.add(itemCrearDi);

        Menulibro1.setText("Libros");

        Menulibro2.setText("Libro");

        jMenuItem26.setText("Crear");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        Menulibro2.add(jMenuItem26);

        jMenuItem27.setText("Modificar");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        Menulibro2.add(jMenuItem27);

        jMenuItem28.setText("Buscar");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        Menulibro2.add(jMenuItem28);

        jMenuItem29.setText("Eliminar");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        Menulibro2.add(jMenuItem29);

        jMenuItem2.setText("Mostrar Libros");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Menulibro2.add(jMenuItem2);

        Menulibro1.add(Menulibro2);

        Menulibro3.setText("Detalles");

        Menuautor2.setText("Autor");
        Menuautor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menuautor2ActionPerformed(evt);
            }
        });

        jMenuItem22.setText("Crear");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        Menuautor2.add(jMenuItem22);

        jMenuItem23.setText("Modificar");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        Menuautor2.add(jMenuItem23);

        itemBuscarAu.setText("Buscar");
        itemBuscarAu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarAuActionPerformed(evt);
            }
        });
        Menuautor2.add(itemBuscarAu);

        jMenuItem25.setText("Eliminar");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        Menuautor2.add(jMenuItem25);

        jMenuItem5.setText("Mostrar Autores");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        Menuautor2.add(jMenuItem5);

        Menulibro3.add(Menuautor2);

        jMenu10.setText("Editorial");

        itemCrearEdi.setText("Crear");
        itemCrearEdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCrearEdiActionPerformed(evt);
            }
        });
        jMenu10.add(itemCrearEdi);

        itemModificarEdi.setText("Modificar");
        itemModificarEdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemModificarEdiActionPerformed(evt);
            }
        });
        jMenu10.add(itemModificarEdi);

        itemBuscarEdi.setText("Buscar");
        itemBuscarEdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarEdiActionPerformed(evt);
            }
        });
        jMenu10.add(itemBuscarEdi);

        itemEliminarEdi.setText("Eliminar");
        itemEliminarEdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarEdiActionPerformed(evt);
            }
        });
        jMenu10.add(itemEliminarEdi);

        jMenuItem6.setText("Mostrar Editorial");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem6);

        Menulibro3.add(jMenu10);

        jMenu14.setText("Categoria");

        jMenuItem18.setText("Crear");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem18);

        jMenuItem19.setText("Modificar");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem19);

        jMenuItem20.setText("Buscar");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem20);

        jMenuItem21.setText("Eliminar");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem21);

        jMenuItem4.setText("Mostrar Categorias");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem4);

        Menulibro3.add(jMenu14);

        Menuautor3.setText("Estado");
        Menuautor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menuautor3ActionPerformed(evt);
            }
        });

        jMenuItem24.setText("Crear");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        Menuautor3.add(jMenuItem24);

        jMenuItem38.setText("Modificar");
        jMenuItem38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem38ActionPerformed(evt);
            }
        });
        Menuautor3.add(jMenuItem38);

        itemBuscarAu1.setText("Buscar");
        itemBuscarAu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarAu1ActionPerformed(evt);
            }
        });
        Menuautor3.add(itemBuscarAu1);

        jMenuItem39.setText("Eliminar");
        jMenuItem39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem39ActionPerformed(evt);
            }
        });
        Menuautor3.add(jMenuItem39);

        jMenuItem40.setText("Mostrar Estados");
        jMenuItem40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem40ActionPerformed(evt);
            }
        });
        Menuautor3.add(jMenuItem40);

        Menulibro3.add(Menuautor3);

        Menuautor4.setText("Idioma");
        Menuautor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menuautor4ActionPerformed(evt);
            }
        });

        jMenuItem41.setText("Crear");
        jMenuItem41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem41ActionPerformed(evt);
            }
        });
        Menuautor4.add(jMenuItem41);

        jMenuItem42.setText("Modificar");
        jMenuItem42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem42ActionPerformed(evt);
            }
        });
        Menuautor4.add(jMenuItem42);

        itemBuscarAu2.setText("Buscar");
        itemBuscarAu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarAu2ActionPerformed(evt);
            }
        });
        Menuautor4.add(itemBuscarAu2);

        jMenuItem43.setText("Eliminar");
        jMenuItem43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem43ActionPerformed(evt);
            }
        });
        Menuautor4.add(jMenuItem43);

        jMenuItem44.setText("Mostrar Idioma");
        jMenuItem44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem44ActionPerformed(evt);
            }
        });
        Menuautor4.add(jMenuItem44);

        Menulibro3.add(Menuautor4);

        Menulibro1.add(Menulibro3);

        jMenuBar1.add(Menulibro1);

        Menufactura.setText("Gestion Factura");

        jMenuItem30.setText("Crear");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        Menufactura.add(jMenuItem30);

        jMenuItem31.setText("Modificar");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        Menufactura.add(jMenuItem31);

        jMenuItem32.setText("Buscar");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        Menufactura.add(jMenuItem32);

        jMenuItem33.setText("Eliminar");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        Menufactura.add(jMenuItem33);

        jMenuBar1.add(Menufactura);

        itemtracrear2.setText("Gestionar Boleta");

        itemCrearTra1.setText("Crear");
        itemCrearTra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCrearTra1ActionPerformed(evt);
            }
        });
        itemtracrear2.add(itemCrearTra1);

        itemModificarTra1.setText("Modificar");
        itemModificarTra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemModificarTra1ActionPerformed(evt);
            }
        });
        itemtracrear2.add(itemModificarTra1);

        itemBuscarTra1.setText("Buscar");
        itemBuscarTra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarTra1ActionPerformed(evt);
            }
        });
        itemtracrear2.add(itemBuscarTra1);

        itemEliminarTra1.setText("Eliminar");
        itemEliminarTra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarTra1ActionPerformed(evt);
            }
        });
        itemtracrear2.add(itemEliminarTra1);

        jMenuBar1.add(itemtracrear2);

        jMenu11.setText("Gestion Compra");

        jMenu12.setText("Metodo de pago");

        itemCrearCli1.setText("Crear");
        itemCrearCli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCrearCli1ActionPerformed(evt);
            }
        });
        jMenu12.add(itemCrearCli1);

        itemCrearCli3.setText("Modificar");
        itemCrearCli3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCrearCli3ActionPerformed(evt);
            }
        });
        jMenu12.add(itemCrearCli3);

        itemCrearCli4.setText("Borrar");
        itemCrearCli4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCrearCli4ActionPerformed(evt);
            }
        });
        jMenu12.add(itemCrearCli4);

        metodopago.setText("Mostra Metodos de Pago");
        metodopago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodopagoActionPerformed(evt);
            }
        });
        jMenu12.add(metodopago);

        jMenu11.add(jMenu12);

        jMenu13.setText("Transaccion");

        jMenuItem34.setText("Compra");
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem34);

        jMenuItem36.setText("Buscar");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem36);

        jMenuItem35.setText("Modificar");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem35);

        jMenuItem37.setText("Eliminar");
        jMenuItem37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem37ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem37);

        jMenu11.add(jMenu13);

        jMenuBar1.add(jMenu11);

        jMenu9.setText("Cliente");

        itemCrearCli.setText("Crear");
        itemCrearCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCrearCliActionPerformed(evt);
            }
        });
        jMenu9.add(itemCrearCli);

        itemModificarCli.setText("Modificar");
        itemModificarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemModificarCliActionPerformed(evt);
            }
        });
        jMenu9.add(itemModificarCli);

        itemBuscarCli.setText("Buscar");
        itemBuscarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarCliActionPerformed(evt);
            }
        });
        jMenu9.add(itemBuscarCli);

        itemEliminarCli.setText("Eliminar");
        itemEliminarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarCliActionPerformed(evt);
            }
        });
        jMenu9.add(itemEliminarCli);

        jMenuBar1.add(jMenu9);

        itemtracrear1.setText("Trabajador");

        itemCrearTra.setText("Crear");
        itemCrearTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCrearTraActionPerformed(evt);
            }
        });
        itemtracrear1.add(itemCrearTra);

        itemModificarTra.setText("Modificar");
        itemModificarTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemModificarTraActionPerformed(evt);
            }
        });
        itemtracrear1.add(itemModificarTra);

        itemBuscarTra.setText("Buscar");
        itemBuscarTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarTraActionPerformed(evt);
            }
        });
        itemtracrear1.add(itemBuscarTra);

        itemEliminarTra.setText("Eliminar");
        itemEliminarTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarTraActionPerformed(evt);
            }
        });
        itemtracrear1.add(itemEliminarTra);

        jMenuBar1.add(itemtracrear1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Mipanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mipanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemBuscarDiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarDiActionPerformed
        if ( BD == null || BD.isClosed()) {
            BD = new BuscarDistribuidora();
            Mipanel.add(BD);
            BD.show();
        }
        else{
            BD.show();
        }
    }//GEN-LAST:event_itemBuscarDiActionPerformed

    private void itemEliminarDIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarDIActionPerformed
        if ( ED == null || ED.isClosed()) {
            ED = new EliminarDistribuidora();
            Mipanel.add(ED);
            ED.show();
        }
        else{
            ED.show();
        }
    }//GEN-LAST:event_itemEliminarDIActionPerformed

    private void itemBuscarEdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarEdiActionPerformed
        if ( BE == null || BE.isClosed()) {
            BE = new BuscarEditorial();
            Mipanel.add(BE);
            BE.show();
        }
        else{
            BE.show();
        }
    }//GEN-LAST:event_itemBuscarEdiActionPerformed

    private void itemEliminarEdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarEdiActionPerformed
        if ( EE == null || EE.isClosed()) {
            EE = new EliminarEditorial();
            Mipanel.add(EE);
            EE.show();
        }
        else{
            EE.show();
        }
    }//GEN-LAST:event_itemEliminarEdiActionPerformed

    private void itemBuscarTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarTraActionPerformed
        if ( BT == null || BT.isClosed()) {
            BT = new BuscarTrabajador();
            Mipanel.add(BT);
            BT.show();
        }
        else{
            BT.show();
        }
    }//GEN-LAST:event_itemBuscarTraActionPerformed

    private void itemEliminarTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarTraActionPerformed
        if ( ET == null || ET.isClosed()) {
            ET = new EliminarTrabajador();
            Mipanel.add(ET);
            ET.show();
        }
        else{
            ET.show();
        }
    }//GEN-LAST:event_itemEliminarTraActionPerformed

    private void itemBuscarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarCliActionPerformed
        if ( BCL == null || BCL.isClosed()) {
            BCL = new BuscarCliente();
            Mipanel.add(BCL);
            BCL.show();
        }
        else{
            BCL.show();
        }
    }//GEN-LAST:event_itemBuscarCliActionPerformed

    private void itemEliminarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarCliActionPerformed
        if ( ECL == null || ECL.isClosed()) {
            ECL = new EliminarCliente();
            Mipanel.add(ECL);
            ECL.show();
        }
        else{
            ECL.show();
        }
    }//GEN-LAST:event_itemEliminarCliActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        if ( BC == null || BC.isClosed()) {
            BC = new BuscarCategoria();
            Mipanel.add(BC);
            BC.show();
        }
        else{
            BC.show();
        }
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        if ( EC == null || EC.isClosed()) {
            EC = new EliminarCategoria();
            Mipanel.add(EC);
            EC.show();
        }
        else{
            EC.show();
        }
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void itemBuscarAuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarAuActionPerformed
        if (BA == null || BA.isClosed()) {
            BA = new BuscarAutor();
            Mipanel.add(BA);
            BA.show();
        }
        else{
            BA.show();
        }
    }//GEN-LAST:event_itemBuscarAuActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        if (EA == null || EA.isClosed()) {
            EA = new EliminarAutor();
            Mipanel.add(EA);
            EA.show();
        }
        else{
            EA.show();
        }
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        if ( BL == null || BL.isClosed()) {
            BL = new BuscarLibro();
            Mipanel.add(BL);
            BL.show();
        }
        else{
            BL.show();
        }
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        if ( EL == null || EL.isClosed()) {
            EL = new EliminarLibro();
            Mipanel.add(EL);
            EL.show();
        }
        else{
            EL.show();
        }
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void itemModificarEdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemModificarEdiActionPerformed
        if ( ME == null || ME.isClosed()) {
            ME = new ModificarEditorial();
            Mipanel.add(ME);
            ME.show();
        }
        else{
            ME.show();
        }
    }//GEN-LAST:event_itemModificarEdiActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        if (CA == null || CA.isClosed()) {
            CA = new CrearAutor();
            Mipanel.add(CA);
            CA.show();
        }
        else{
            CA.show();
        }
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        if (MA == null || MA.isClosed()) {
            MA = new ModificarAutor();
            Mipanel.add(MA);
            MA.show();
        }
        else{
            MA.show();
        }
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (CD == null || CD.isClosed()) {
            CD = new CrearDistribuidora();
            Mipanel.add(CD);
            CD.show();
        }
        else{
            CD.show();
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void itemModficarDiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemModficarDiActionPerformed
        if ( MD == null || MD.isClosed()) {
            MD = new ModificarDistribuidora();
            Mipanel.add(MD);
            MD.show();
        }
        else{
            MD.show();
        }
    }//GEN-LAST:event_itemModficarDiActionPerformed

    private void itemCrearEdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCrearEdiActionPerformed
        if ( CE == null || CE.isClosed()) {
            CE = new CrearEditorial();
            Mipanel.add(CE);
            CE.show();
        }
        else{
            CE.show();
        }
    }//GEN-LAST:event_itemCrearEdiActionPerformed

    private void itemCrearTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCrearTraActionPerformed
        if ( CT == null || CT.isClosed()) {
            CT = new CrearTrabajador();
            Mipanel.add(CT);
            CT.show();
        }
        else{
            CT.show();
        }
    }//GEN-LAST:event_itemCrearTraActionPerformed

    private void itemModificarTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemModificarTraActionPerformed
        if ( MT == null || MT.isClosed()) {
            MT = new ModificarTrabajador();
            Mipanel.add(MT);
            MT.show();
        }
        else{
            MT.show();
        }
    }//GEN-LAST:event_itemModificarTraActionPerformed

    private void itemCrearCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCrearCliActionPerformed
        if ( CCL == null || CCL.isClosed()) {
            CCL = new CrearCliente();
            Mipanel.add(CCL);
            CCL.show();
        }
        else{
            CCL.show();
        }
    }//GEN-LAST:event_itemCrearCliActionPerformed

    private void itemModificarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemModificarCliActionPerformed
        if ( MCL == null || MCL.isClosed()) {
            MCL = new ModificarCliente();
            Mipanel.add(MCL);
            MCL.show();
        }
        else{
            MCL.show();
        }
    }//GEN-LAST:event_itemModificarCliActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        if ( CC == null || CC.isClosed()) {
            CC = new CrearCategoria();
            Mipanel.add(CC);
            CC.show();
        }
        else{
            CC.show();
        }
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        if ( MC == null || MC.isClosed()) {
            MC = new ModificarCategoria();
            Mipanel.add(MC);
            MC.show();
        }
        else{
            MC.show();
        }
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        if ( CL == null || CL.isClosed()) {
            CL = new CrearLibro();
            Mipanel.add(CL);
            CL.show();
        }
        else{
            CL.show();
        }
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        if ( ML == null || ML.isClosed()) {
            ML = new ModificarLibro();
            Mipanel.add(ML);
            ML.show();
        }
        else{
            ML.show();
        }
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
        if ( CF == null || CF.isClosed()) {
            CF = new CrearFactura();
            Mipanel.add(CF);
            CF.show();
        }
        else{
            CF.show();
        }
         
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
        if ( MF == null || MF.isClosed()) {
            MF = new ModificarFactura();
            Mipanel.add(MF);
            MF.show();
        }
        else{
            MF.show();
        }
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
        if ( BF == null || BF.isClosed()) {
            BF = new BuscarFactura();
            Mipanel.add(BF);
            BF.show();
        }
        else{
            BF.show();
        }
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
        if ( EF == null || EF.isClosed()) {
            EF = new EliminarFactura();
            Mipanel.add(EF);
            EF.show();
        }
        else{
            EF.show();
        }
    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed
        if ( CCR == null || CCR.isClosed()) {
            CCR = new CrearCompra();
            Mipanel.add(CCR);
            CCR.show();
        }
        else{
            CCR.show();
        }
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
        if ( MCR == null || MCR.isClosed()) {
            MCR = new ModificarComprar();
            Mipanel.add(MCR);
            MCR.show();
        }
        else{
            MCR.show();
        }
    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
        if ( BCR == null || BCR.isClosed()) {
            BCR = new BuscarComprar();
            Mipanel.add(BCR);
            BCR.show();
        }
        else{
            BCR.show();
        }
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void jMenuItem37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem37ActionPerformed
        if ( AC == null || AC.isClosed()) {
            AC = new AnularComprar();
            Mipanel.add(AC);
            AC.show();
        }
        else{
            AC.show();
        }
    }//GEN-LAST:event_jMenuItem37ActionPerformed

    private void itemmostrartodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemmostrartodosActionPerformed
        if ( MTD == null || MTD.isClosed()) {
            MTD = new MostrarDistribuidores();
            Mipanel.add(MTD);
            MTD.show();
        }
        else{
            MTD.show();
        }
    }//GEN-LAST:event_itemmostrartodosActionPerformed

    private void itemCrearDiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCrearDiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCrearDiActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if ( MTL == null || MTL.isClosed()) {
            MTL = new Mostrartodolibros();
            Mipanel.add(MTL);
            MTL.show();
        }
        else{
            MTL.show();
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void Menuautor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menuautor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menuautor2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if ( MTC == null || MTC.isClosed()) {
            MTC = new MostrarCategorias();
            Mipanel.add(MTC);
            MTC.show();
        }
        else{
            MTC.show();
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        if ( CDD == null || CDD.isClosed()) {
            CDD = new CrearDescripcion();
            Mipanel.add(CDD);
            CDD.show();
        }
        else{
            CDD.show();
        }
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem38ActionPerformed
        if ( MDD == null || MDD.isClosed()) {
            MDD = new ModificarDescripcion();
            Mipanel.add(MDD);
            MDD.show();
        }
        else{
            MDD.show();
        }
    }//GEN-LAST:event_jMenuItem38ActionPerformed

    private void itemBuscarAu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarAu1ActionPerformed
        if ( BDD == null || BDD.isClosed()) {
            BDD = new BuscarDescripcion();
            Mipanel.add(BDD);
            BDD.show();
        }
        else{
            BDD.show();
        }
    }//GEN-LAST:event_itemBuscarAu1ActionPerformed

    private void jMenuItem39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem39ActionPerformed
        if ( EDD == null || EDD.isClosed()) {
            EDD = new EliminarDescripcion();
            Mipanel.add(EDD);
            EDD.show();
        }
        else{
            EDD.show();
        }
    }//GEN-LAST:event_jMenuItem39ActionPerformed

    private void Menuautor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menuautor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menuautor3ActionPerformed

    private void jMenuItem40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem40ActionPerformed
        if ( MDDD == null || MDDD.isClosed()) {
            MDDD = new MostrarDescripcion();
            Mipanel.add(MDDD);
            MDDD.show();
        }
        else{
            MDDD.show();
        }
    }//GEN-LAST:event_jMenuItem40ActionPerformed

    private void jMenuItem41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem41ActionPerformed

    private void jMenuItem42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem42ActionPerformed

    private void itemBuscarAu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarAu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemBuscarAu2ActionPerformed

    private void jMenuItem43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem43ActionPerformed

    private void jMenuItem44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem44ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem44ActionPerformed

    private void Menuautor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menuautor4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menuautor4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if ( MTA == null || MTA.isClosed()) {
            MTA = new MostraAutores();
            Mipanel.add(MTA);
            MTA.show();
        }
        else{
            MTA.show();
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        if ( MTE == null || MTE.isClosed()) {
            MTE = new MostrarEditorial();
            Mipanel.add(MTE);
            MTE.show();
        }
        else{
            MTE.show();
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void itemCrearCli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCrearCli1ActionPerformed
        if ( CMP == null || CMP.isClosed()) {
            CMP = new CrearMetododepago();
            Mipanel.add(CMP);
            CMP.show();
        }
        else{
            CMP.show();
        }
    }//GEN-LAST:event_itemCrearCli1ActionPerformed

    private void itemCrearCli3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCrearCli3ActionPerformed
        if ( MMP == null || MMP.isClosed()) {
            MMP = new ModificarMetododepago();
            Mipanel.add(MMP);
            MMP.show();
        }
        else{
            MMP.show();
        }
    }//GEN-LAST:event_itemCrearCli3ActionPerformed

    private void itemCrearCli4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCrearCli4ActionPerformed
        if ( EMP == null || EMP.isClosed()) {
            EMP = new EliminarMetododepago();
            Mipanel.add(EMP);
            EMP.show();
        }
        else{
            EMP.show();
        }
    }//GEN-LAST:event_itemCrearCli4ActionPerformed

    private void metodopagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodopagoActionPerformed
        if ( MMP1 == null || MMP1.isClosed()) {
            MMP1 = new MostrarMetodosdepago();
            Mipanel.add(MMP1);
            MMP1.show();
        }
        else{
            MMP1.show();
        }
    }//GEN-LAST:event_metodopagoActionPerformed

    private void itemCrearTra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCrearTra1ActionPerformed
        if ( CB == null || CB.isClosed()) {
            CB = new CrearBoleta();
            Mipanel.add(CB);
            CB.show();
        }
        else{
            CB.show();
        }
    }//GEN-LAST:event_itemCrearTra1ActionPerformed

    private void itemModificarTra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemModificarTra1ActionPerformed
        if ( MB == null || MB.isClosed()) {
            MB = new ModificarBoleta();
            Mipanel.add(MB);
            MB.show();
        }
        else{
            MB.show();
        }
    }//GEN-LAST:event_itemModificarTra1ActionPerformed

    private void itemBuscarTra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarTra1ActionPerformed
        if ( BB == null || BB.isClosed()) {
            BB = new BuscarBoleta();
            Mipanel.add(MB);
            BB.show();
        }
        else{
            BB.show();
        }
    }//GEN-LAST:event_itemBuscarTra1ActionPerformed

    private void itemEliminarTra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarTra1ActionPerformed
        if ( EB == null || EB.isClosed()) {
            EB = new EliminarBoleta();
            Mipanel.add(EB);
            EB.show();
        }
        else{
            EB.show();
        }
    }//GEN-LAST:event_itemEliminarTra1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
    BuscarAutor BA;
    EliminarAutor EA;
    ModificarAutor MA;
    CrearAutor CA;
    MostraAutores MTA;
    
    BuscarCategoria BC;
    EliminarCategoria EC;
    ModificarCategoria MC;
    CrearCategoria CC;
    MostrarCategorias MTC;
    
    BuscarCliente BCL;
    EliminarCliente ECL;
    ModificarCliente MCL;
    CrearCliente CCL;
    
    BuscarDistribuidora BD;
    EliminarDistribuidora  ED;
    ModificarDistribuidora  MD;
    CrearDistribuidora CD;
    MostrarDistribuidores MTD;
    
    BuscarEditorial BE;
    EliminarEditorial  EE;
    ModificarEditorial  ME;
    CrearEditorial CE;
    MostrarEditorial MTE;
    
    BuscarTrabajador BT;
    EliminarTrabajador ET;
    ModificarTrabajador MT;
    CrearTrabajador CT;
    
    BuscarLibro BL;
    EliminarLibro  EL;
    ModificarLibro  ML;
    CrearLibro  CL;
    Mostrartodolibros MTL;
    
    BuscarFactura BF;
    CrearFactura CF;
    EliminarFactura EF;
    ModificarFactura MF;
    
    CrearMetododepago CMP;
    EliminarMetododepago EMP;
    ModificarMetododepago MMP;
    MostrarMetodosdepago MMP1;
    
    BuscarComprar BCR;
    CrearCompra CCR;
    AnularComprar AC;
    ModificarComprar MCR;
    
    BuscarDescripcion BDD;
    CrearDescripcion CDD;
    EliminarDescripcion EDD;
    ModificarDescripcion MDD;
    MostrarDescripcion MDDD;
    
    BuscarBoleta BB;
    CrearBoleta CB;
    EliminarBoleta EB;
    ModificarBoleta MB;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menuautor2;
    private javax.swing.JMenu Menuautor3;
    private javax.swing.JMenu Menuautor4;
    private javax.swing.JMenu Menufactura;
    private javax.swing.JMenu Menulibro1;
    private javax.swing.JMenu Menulibro2;
    private javax.swing.JMenu Menulibro3;
    private javax.swing.JPanel Mipanel;
    private javax.swing.JMenuItem itemBuscarAu;
    private javax.swing.JMenuItem itemBuscarAu1;
    private javax.swing.JMenuItem itemBuscarAu2;
    private javax.swing.JMenuItem itemBuscarCli;
    private javax.swing.JMenuItem itemBuscarDi;
    private javax.swing.JMenuItem itemBuscarEdi;
    private javax.swing.JMenuItem itemBuscarTra;
    private javax.swing.JMenuItem itemBuscarTra1;
    private javax.swing.JMenuItem itemCrearCli;
    private javax.swing.JMenuItem itemCrearCli1;
    private javax.swing.JMenuItem itemCrearCli3;
    private javax.swing.JMenuItem itemCrearCli4;
    private javax.swing.JMenu itemCrearDi;
    private javax.swing.JMenuItem itemCrearEdi;
    private javax.swing.JMenuItem itemCrearTra;
    private javax.swing.JMenuItem itemCrearTra1;
    private javax.swing.JMenuItem itemEliminarCli;
    private javax.swing.JMenuItem itemEliminarDI;
    private javax.swing.JMenuItem itemEliminarEdi;
    private javax.swing.JMenuItem itemEliminarTra;
    private javax.swing.JMenuItem itemEliminarTra1;
    private javax.swing.JMenuItem itemModficarDi;
    private javax.swing.JMenuItem itemModificarCli;
    private javax.swing.JMenuItem itemModificarEdi;
    private javax.swing.JMenuItem itemModificarTra;
    private javax.swing.JMenuItem itemModificarTra1;
    private javax.swing.JMenuItem itemmostrartodos;
    private javax.swing.JMenu itemtracrear1;
    private javax.swing.JMenu itemtracrear2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem metodopago;
    // End of variables declaration//GEN-END:variables
}
