/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Factura;


import Conexion.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class BuscarFactura extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarFactura1
     */
    public BuscarFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mipanel = new javax.swing.JPanel();
        txtfolio = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        lblfolio = new javax.swing.JLabel();
        lblprecioneto = new javax.swing.JLabel();
        lblcostoiva = new javax.swing.JLabel();
        lblpreciototal = new javax.swing.JLabel();
        lblfechacompra = new javax.swing.JLabel();
        lblhoradecompra = new javax.swing.JLabel();
        lblmetododepago = new javax.swing.JLabel();
        lbldistribuidora = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        lblfolio.setText("Folio");

        lblprecioneto.setText("Precio neto :");

        lblcostoiva.setText("Costo IVA :");

        lblpreciototal.setText("Precio total :");

        lblfechacompra.setText("Fecha de compra :");

        lblhoradecompra.setText("Hora de compra :");

        lblmetododepago.setText("Método de pago :");

        lbldistribuidora.setText("Distribuidor involucrado :");

        javax.swing.GroupLayout mipanelLayout = new javax.swing.GroupLayout(mipanel);
        mipanel.setLayout(mipanelLayout);
        mipanelLayout.setHorizontalGroup(
            mipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mipanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(mipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mipanelLayout.createSequentialGroup()
                        .addComponent(lblfolio)
                        .addGap(44, 44, 44)
                        .addComponent(txtfolio, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbldistribuidora, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblprecioneto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblpreciototal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblcostoiva, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblfechacompra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                        .addComponent(lblhoradecompra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblmetododepago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        mipanelLayout.setVerticalGroup(
            mipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mipanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(mipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfolio)
                    .addComponent(txtfolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addGap(47, 47, 47)
                .addComponent(lblprecioneto)
                .addGap(23, 23, 23)
                .addComponent(lblpreciototal)
                .addGap(18, 18, 18)
                .addComponent(lblcostoiva)
                .addGap(18, 18, 18)
                .addComponent(lblfechacompra)
                .addGap(18, 18, 18)
                .addComponent(lblhoradecompra)
                .addGap(31, 31, 31)
                .addComponent(lblmetododepago, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbldistribuidora)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mipanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mipanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        try {                                          
            Conexion ObjetoConexion = new Conexion();
            
            String folio = txtfolio.getText();
            
            if (folio.trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Complete el espacio en blanco"); 
            }
            
            String query = "Select * from factura where folio_fac = '"+folio+"'";
            
            state = ObjetoConexion.getCon().createStatement();
            
            res = state.executeQuery(query);
            
            if (res.next()) {

                lblprecioneto.setText("Precio neto : "+res.getString("precio_neto"));
                lblcostoiva.setText("Costo IVA :" + res.getString("costo_iva"));
                lblpreciototal.setText("Precio total :" + res.getString("precio_total"));
                lblfechacompra.setText("Fecha de compra : "+res.getString("fecha_compra"));
                lblhoradecompra.setText("Hora de compra : "+res.getString("hora"));
                lblmetododepago.setText("Método de pago : "+res.getString("cod_metod"));
                lbldistribuidora.setText("Distribuidor involucrado : "+res.getString("rut_dis"));
                
            }
            else{
                JOptionPane.showMessageDialog(this, "No hay Registro");

                lblprecioneto.setText("Precio neto : ");
                lblcostoiva.setText("Costo IVA :" );
                lblpreciototal.setText("Precio total :");
                lblfechacompra.setText("Fecha de compra : ");
                lblhoradecompra.setText("Hora de compra : ");
                lblmetododepago.setText("Método de pago : ");
                lbldistribuidora.setText("Distribuidor involucrado :");

            }
        }
        catch (SQLException ex) {
            Logger.getLogger(BuscarFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    ResultSet res;
    Statement state;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JLabel lblcostoiva;
    private javax.swing.JLabel lbldistribuidora;
    private javax.swing.JLabel lblfechacompra;
    private javax.swing.JLabel lblfolio;
    private javax.swing.JLabel lblhoradecompra;
    private javax.swing.JLabel lblmetododepago;
    private javax.swing.JLabel lblprecioneto;
    private javax.swing.JLabel lblpreciototal;
    private javax.swing.JPanel mipanel;
    private javax.swing.JTextField txtfolio;
    // End of variables declaration//GEN-END:variables
}
