/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Factura;

import Conexion.Conexion;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class CrearFactura extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearFactura
     */
    public CrearFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        Mipanel = new javax.swing.JPanel();
        lblfolio = new javax.swing.JLabel();
        lblprecioneto = new javax.swing.JLabel();
        lblprecioconiva = new javax.swing.JLabel();
        lblcostoiva = new javax.swing.JLabel();
        lblfechacompra = new javax.swing.JLabel();
        lblhoradecompra = new javax.swing.JLabel();
        lbldistribuidora = new javax.swing.JLabel();
        lblmetododepago = new javax.swing.JLabel();
        txtfolio = new javax.swing.JTextField();
        txtprecioneto = new javax.swing.JTextField();
        txtpreciototal = new javax.swing.JTextField();
        txtcostoiva = new javax.swing.JTextField();
        txtfechadecompra = new javax.swing.JTextField();
        txthoradecomprar = new javax.swing.JTextField();
        txtdistribuidor = new javax.swing.JTextField();
        txtmetododepago = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lblfolio.setText("Folio");

        lblprecioneto.setText("Precio neto");

        lblprecioconiva.setText("Precio total");

        lblcostoiva.setText("Costo IVA");

        lblfechacompra.setText("Fecha de compra");

        lblhoradecompra.setText("Hora de compra");

        lbldistribuidora.setText("Distribuidor involucrado");

        lblmetododepago.setText("Método de pago");

        txtcostoiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcostoivaActionPerformed(evt);
            }
        });

        txtdistribuidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdistribuidorActionPerformed(evt);
            }
        });

        txtmetododepago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmetododepagoActionPerformed(evt);
            }
        });

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MipanelLayout = new javax.swing.GroupLayout(Mipanel);
        Mipanel.setLayout(MipanelLayout);
        MipanelLayout.setHorizontalGroup(
            MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MipanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblfolio)
                    .addComponent(lblfechacompra)
                    .addComponent(lblmetododepago)
                    .addComponent(lbldistribuidora)
                    .addComponent(lblhoradecompra)
                    .addComponent(lblprecioconiva)
                    .addComponent(lblprecioneto)
                    .addComponent(lblcostoiva))
                .addGap(33, 33, 33)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MipanelLayout.createSequentialGroup()
                        .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfechadecompra, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprecioneto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfolio, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpreciototal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcostoiva, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(MipanelLayout.createSequentialGroup()
                        .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txthoradecomprar, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(txtdistribuidor, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(txtmetododepago, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        MipanelLayout.setVerticalGroup(
            MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MipanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfolio)
                    .addComponent(txtfolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprecioneto)
                    .addComponent(txtprecioneto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcostoiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcostoiva))
                .addGap(18, 18, 18)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpreciototal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblprecioconiva))
                .addGap(17, 17, 17)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfechacompra)
                    .addComponent(txtfechadecompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhoradecompra)
                    .addComponent(txthoradecomprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmetododepago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmetododepago))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdistribuidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldistribuidora))
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mipanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mipanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdistribuidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdistribuidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdistribuidorActionPerformed

    private void txtmetododepagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmetododepagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmetododepagoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {                                             
            
            Conexion ObjetoConexion = new Conexion();

            String folio_fac = txtfolio.getText();
            String precio_neto = txtprecioneto.getText();
            String costo_iva = txtcostoiva.getText();
            String precio_total = txtpreciototal.getText();
            String fecha_compra = txtfechadecompra.getText();
            String hora = txthoradecomprar.getText();
            String cod_metod = txtmetododepago.getText();
            String rut_dis = txtdistribuidor.getText();
            
            int folio  = 0;
                 
            if (folio_fac.trim().equals("")|| precio_neto.trim().equals("")|| costo_iva.trim().equals("")||
                    precio_total.trim().equals("")|| fecha_compra.trim().equals("")|| hora.trim().equals("")||
                    cod_metod.trim().equals("")||rut_dis.trim().equals("")) {
                
                JOptionPane.showMessageDialog(this, "Complete los espacios en blanco");
            }
        try{
            
            folio =Integer.parseInt(folio_fac);

            String query = "insert into factura(folio_fac,precio_neto,costo_iva,precio_total,fecha_compra,hora,cod_metod,rut_dis) "
                    + "values ('"+folio_fac+"','"+precio_neto+"','"+costo_iva+"'"
                    + ",'"+precio_total+"','"+fecha_compra+"','"+hora+"','"+cod_metod+"','"+rut_dis+"')";
            
           
            
            state = ObjetoConexion.getCon().createStatement();

            try{
                int x = state.executeUpdate(query);

                if (x > 0) {
                JOptionPane.showMessageDialog(this, "Registrado Correctamente");
                }
                else{
                JOptionPane.showMessageDialog(this, "No se pudo Registrar");
                }
            }
            catch(SQLException error){
                JOptionPane.showMessageDialog(this, "Folio ya registrado");
                System.out.println(state.executeUpdate(query));
               
            }

            }
        catch(NumberFormatException error){
        }


        } catch (SQLException ex) {
        Logger.getLogger(CrearFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtcostoivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcostoivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcostoivaActionPerformed

    Statement state;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Mipanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblcostoiva;
    private javax.swing.JLabel lbldistribuidora;
    private javax.swing.JLabel lblfechacompra;
    private javax.swing.JLabel lblfolio;
    private javax.swing.JLabel lblhoradecompra;
    private javax.swing.JLabel lblmetododepago;
    private javax.swing.JLabel lblprecioconiva;
    private javax.swing.JLabel lblprecioneto;
    private javax.swing.JTextField txtcostoiva;
    private javax.swing.JTextField txtdistribuidor;
    private javax.swing.JTextField txtfechadecompra;
    private javax.swing.JTextField txtfolio;
    private javax.swing.JTextField txthoradecomprar;
    private javax.swing.JTextField txtmetododepago;
    private javax.swing.JTextField txtprecioneto;
    private javax.swing.JTextField txtpreciototal;
    // End of variables declaration//GEN-END:variables
}
