/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Libro;

import Autor.BuscarAutor;
import Conexion.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class BuscarLibro extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarLibro
     */
    public BuscarLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mipanel = new javax.swing.JPanel();
        lblserie = new javax.swing.JLabel();
        lblnumero = new javax.swing.JLabel();
        lbltitulo = new javax.swing.JLabel();
        lblnumpag = new javax.swing.JLabel();
        lblprecio = new javax.swing.JLabel();
        lblaños = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JButton();
        txtnumeroserie = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        lblEditorial = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lblserie.setText("Serie :");

        lblnumero.setText("ISBN:");

        lbltitulo.setText("Titulo:");

        lblnumpag.setText("Numero de Paginas:");

        lblprecio.setText("Precio de Referencia:");

        lblaños.setText("Año:");

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        lblEstado.setText("Estado");

        lblEditorial.setText("Editorial");

        javax.swing.GroupLayout MipanelLayout = new javax.swing.GroupLayout(Mipanel);
        Mipanel.setLayout(MipanelLayout);
        MipanelLayout.setHorizontalGroup(
            MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MipanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MipanelLayout.createSequentialGroup()
                        .addComponent(lblnumero)
                        .addGap(18, 18, 18)
                        .addComponent(txtnumeroserie, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(MipanelLayout.createSequentialGroup()
                        .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblnumpag, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                .addComponent(lblprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblaños, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblserie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        MipanelLayout.setVerticalGroup(
            MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MipanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnumero)
                    .addComponent(txtnumeroserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addGap(36, 36, 36)
                .addComponent(lblserie)
                .addGap(18, 18, 18)
                .addComponent(lbltitulo)
                .addGap(18, 18, 18)
                .addComponent(lblnumpag)
                .addGap(18, 18, 18)
                .addComponent(lblprecio)
                .addGap(18, 18, 18)
                .addComponent(lblaños)
                .addGap(18, 18, 18)
                .addComponent(lblEstado)
                .addGap(18, 18, 18)
                .addComponent(lblEditorial)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mipanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Mipanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        try {                                          
            Conexion ObjetoConexion = new Conexion();
            
            String numero_serie = txtnumeroserie.getText();
            
            if (numero_serie.trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Complete el espacio en blanco"); 
            }
            
            String query = "Select * from libro where isbn = '"+numero_serie+"'";
            
            //String query = "Select libro.isbn,libro.titulo,libro.paginas,libro.precio,libro.año,estado.descripcion from libro inner join estado on libro.serie= estado.cod_estado";
            
            state = ObjetoConexion.getCon().createStatement();
            
            res = state.executeQuery(query);
            
            if (res.next()) {

                lblserie.setText("Serie: "+res.getString("serie"));
                lbltitulo.setText("Titulo :" + res.getString("titulo"));
                lblnumpag.setText("Numero de Paginas :" + res.getString("paginas"));
                lblprecio.setText("Precio referencia: "+res.getString("precio"));
                lblaños.setText("Año de publicacion: "+res.getString("año"));
                lblEstado.setText("Estado : "+res.getString("cod_estado"));
                lblEditorial.setText("Editorial: "+res.getString("cod_edi"));
                
            }
            else{
                JOptionPane.showMessageDialog(this, "No hay Registro");

                lblserie.setText("ISBN :");
                lbltitulo.setText("Titulo :");
                lblnumpag.setText("Numero de Paginas :");
                lblprecio.setText("Precio :");
                lblaños.setText("Año :");
                lblEstado.setText("Estado :");
                lblEditorial.setText("Editorial:");

            }
        }
        catch (SQLException ex) {
            Logger.getLogger(BuscarLibro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    ResultSet res;
    Statement state;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Mipanel;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JLabel lblEditorial;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblaños;
    private javax.swing.JLabel lblnumero;
    private javax.swing.JLabel lblnumpag;
    private javax.swing.JLabel lblprecio;
    private javax.swing.JLabel lblserie;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JTextField txtnumeroserie;
    // End of variables declaration//GEN-END:variables
}
