/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Libro;

import Autor.CrearAutor;
import Conexion.Conexion;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class CrearLibro extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearLibro
     */
    public CrearLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mipanel = new javax.swing.JPanel();
        lblnumero = new javax.swing.JLabel();
        txtnumero = new javax.swing.JTextField();
        txtisbm = new javax.swing.JTextField();
        txttitulo = new javax.swing.JTextField();
        txtnumpag = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        txtaño = new javax.swing.JTextField();
        lblaños = new javax.swing.JLabel();
        lblprecio = new javax.swing.JLabel();
        lblnumpag = new javax.swing.JLabel();
        lbltitulo = new javax.swing.JLabel();
        lblisbm = new javax.swing.JLabel();
        btncrear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtestado = new javax.swing.JTextField();
        txteditorial = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lblnumero.setText("Numero de Serie:");

        lblaños.setText("Año:");

        lblprecio.setText("Precio de Referencia:");

        lblnumpag.setText("Numero de Paginas:");

        lbltitulo.setText("Titulo:");

        lblisbm.setText("ISBN:");

        btncrear.setText("Crear");
        btncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearActionPerformed(evt);
            }
        });

        jLabel1.setText("Estado");

        jLabel2.setText("Editorial");

        javax.swing.GroupLayout MipanelLayout = new javax.swing.GroupLayout(Mipanel);
        Mipanel.setLayout(MipanelLayout);
        MipanelLayout.setHorizontalGroup(
            MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MipanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnumero)
                    .addComponent(lblisbm)
                    .addComponent(lbltitulo)
                    .addComponent(lblnumpag)
                    .addComponent(lblprecio)
                    .addComponent(lblaños)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(47, 47, 47)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtaño, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(txtprecio)
                        .addComponent(txtnumpag)
                        .addComponent(txtisbm)
                        .addComponent(txtnumero)
                        .addComponent(txttitulo)
                        .addComponent(txtestado)
                        .addComponent(txteditorial)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        MipanelLayout.setVerticalGroup(
            MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MipanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnumero)
                    .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblisbm)
                    .addComponent(txtisbm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltitulo)
                    .addComponent(txttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnumpag)
                    .addComponent(txtnumpag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprecio)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblaños)
                    .addComponent(txtaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txteditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btncrear)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mipanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Mipanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearActionPerformed
    try {                                             
            
            Conexion ObjetoConexion = new Conexion();
            
            String numero_serie = txtnumero.getText();
            String isbm = txtisbm.getText();
            String titulo = txttitulo.getText();
            String pagina = txtnumpag.getText();
            String Precio = txtprecio.getText();
            String Año = txtaño.getText();
            String estado = txtestado.getText();
            String editorial = txteditorial.getText();
            
            int numpag = 0;
            int precio = 0;
            int año = 0;
                 
            if (numero_serie.trim().equals("")|| isbm.trim().equals("")|| titulo.trim().equals("")||
                    pagina.trim().equals("")||Precio.trim().equals("")||Año.trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Complete los espacios en blanco");
            }
        try{
            
            numpag =Integer.parseInt(pagina);
            precio =Integer.parseInt(Precio);
            año =Integer.parseInt(Año);

            String query = " insert into libro(serie,isbn,titulo,paginas,precio,año,cod_estado,cod_edi)"
                    + " values ('"+numero_serie+"','"+isbm+"','"+titulo+"','"+numpag+"','"+precio+"'"
                    + ",'"+año+"','"+estado+"','"+editorial+"')";

            state = ObjetoConexion.getCon().createStatement();

            try{
                int x = state.executeUpdate(query);

                if (x > 0) {
                JOptionPane.showMessageDialog(this, "Registrado Correctamente");
            }
                else{
                JOptionPane.showMessageDialog(this, "No se pudo Registrar");
                }
            }
            catch(SQLException error){
                JOptionPane.showMessageDialog(this, "Serie ya registrado");
            }

            }
        catch(NumberFormatException error){
        }


        } catch (SQLException ex) {
        Logger.getLogger(CrearLibro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btncrearActionPerformed

    Statement state;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Mipanel;
    private javax.swing.JButton btncrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblaños;
    private javax.swing.JLabel lblisbm;
    private javax.swing.JLabel lblnumero;
    private javax.swing.JLabel lblnumpag;
    private javax.swing.JLabel lblprecio;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JTextField txtaño;
    private javax.swing.JTextField txteditorial;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtisbm;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtnumpag;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txttitulo;
    // End of variables declaration//GEN-END:variables
}
