/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Boleta;

import Autor.CrearAutor;
import Conexion.Conexion;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class CrearBoleta extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearBoleta
     */
    public CrearBoleta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mipanel = new javax.swing.JPanel();
        lblfolio = new javax.swing.JLabel();
        lblprecioneto = new javax.swing.JLabel();
        lblprecioconiva = new javax.swing.JLabel();
        lblcostoiva = new javax.swing.JLabel();
        lblfechacompra = new javax.swing.JLabel();
        lblhoradecompra = new javax.swing.JLabel();
        lbldistribuidora = new javax.swing.JLabel();
        lblmetododepago = new javax.swing.JLabel();
        txtmetododepago = new javax.swing.JTextField();
        txtcliente = new javax.swing.JTextField();
        txthoradecomprar = new javax.swing.JTextField();
        txtfechadecompra = new javax.swing.JTextField();
        txtcostoiva = new javax.swing.JTextField();
        txtprecioconiva = new javax.swing.JTextField();
        txtprecioneto = new javax.swing.JTextField();
        txtfolio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txttra = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lblfolio.setText("Folio");

        lblprecioneto.setText("Precio neto");

        lblprecioconiva.setText("Precio total");

        lblcostoiva.setText("Costo IVA");

        lblfechacompra.setText("Fecha de compra");

        lblhoradecompra.setText("Hora de compra");

        lbldistribuidora.setText("Cliente");

        lblmetododepago.setText("Método de pago");

        txtmetododepago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmetododepagoActionPerformed(evt);
            }
        });

        txtcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclienteActionPerformed(evt);
            }
        });

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Trabajador");

        txttra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MipanelLayout = new javax.swing.GroupLayout(Mipanel);
        Mipanel.setLayout(MipanelLayout);
        MipanelLayout.setHorizontalGroup(
            MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MipanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblfolio)
                    .addComponent(lblprecioneto)
                    .addComponent(lblfechacompra)
                    .addComponent(lblmetododepago)
                    .addComponent(lbldistribuidora)
                    .addComponent(lblhoradecompra)
                    .addComponent(lblcostoiva)
                    .addComponent(lblprecioconiva)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfechadecompra, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(txtprecioneto, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(txtfolio, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(txtprecioconiva, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(txtcostoiva, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(txthoradecomprar)
                    .addComponent(txtcliente)
                    .addComponent(txtmetododepago)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(txttra))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        MipanelLayout.setVerticalGroup(
            MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MipanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfolio)
                    .addComponent(txtfolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprecioneto)
                    .addComponent(txtprecioneto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprecioconiva)
                    .addComponent(txtprecioconiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblcostoiva)
                    .addComponent(txtcostoiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfechacompra)
                    .addComponent(txtfechadecompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhoradecompra)
                    .addComponent(txthoradecomprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldistribuidora)
                    .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmetododepago)
                    .addComponent(txtmetododepago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txttra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mipanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mipanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmetododepagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmetododepagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmetododepagoActionPerformed

    private void txtclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {                                             
            
            Conexion ObjetoConexion = new Conexion();
            
            String folio = txtfolio.getText();
            String precio_neto = txtprecioneto.getText();
            String precio_total= txtprecioconiva.getText();
            String costoiva = txtcostoiva.getText();
            String fechadecompra = txtfechadecompra.getText();
            String horadecomprar = txthoradecomprar.getText();
            String cliente = txtcliente.getText();
            String metododepago = txtmetododepago.getText();
            String trabajador = txttra.getText();
            
            int folio2=0;
                 
            if (folio.trim().equals("")||precio_neto.trim().equals("")|| precio_total.trim().equals("")|| costoiva.trim().equals("")
                    || fechadecompra.trim().equals("")|| horadecomprar.trim().equals("")|| cliente.trim().equals("")
                    || metododepago.trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Complete los espacios en blanco");
            }
        try{
            
            folio2 =Integer.parseInt(folio);

            String query = " insert into boleta(folio_boleta,precio_neto,costo_iva,precio_total,fecha_venta,hora,cod_metod,rut_cli,rut_trab) values ('"+folio+"','"+precio_neto+"','"+costoiva+"','"+precio_total+"'"
                    + ",'"+fechadecompra+"','"+horadecomprar+"','"
                    + ",'"+metododepago+"','"+cliente+"','"+trabajador+"')";

            state = ObjetoConexion.getCon().createStatement();

            try{
            int x = state.executeUpdate(query);

            if (x > 0) {
                JOptionPane.showMessageDialog(this, "Registrado Correctamente");
            }
            else{
                JOptionPane.showMessageDialog(this, "No se pudo Registrar");
              }
            }
            catch(SQLException error){
                JOptionPane.showMessageDialog(this, "Folio ya registrado");
                System.out.println(state.executeUpdate(query));
            }

            }
        catch(NumberFormatException error){
        }


        } catch (SQLException ex) {
        Logger.getLogger(CrearAutor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txttraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttraActionPerformed

    Connection con;
    Statement state;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Mipanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblcostoiva;
    private javax.swing.JLabel lbldistribuidora;
    private javax.swing.JLabel lblfechacompra;
    private javax.swing.JLabel lblfolio;
    private javax.swing.JLabel lblhoradecompra;
    private javax.swing.JLabel lblmetododepago;
    private javax.swing.JLabel lblprecioconiva;
    private javax.swing.JLabel lblprecioneto;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtcostoiva;
    private javax.swing.JTextField txtfechadecompra;
    private javax.swing.JTextField txtfolio;
    private javax.swing.JTextField txthoradecomprar;
    private javax.swing.JTextField txtmetododepago;
    private javax.swing.JTextField txtprecioconiva;
    private javax.swing.JTextField txtprecioneto;
    private javax.swing.JTextField txttra;
    // End of variables declaration//GEN-END:variables
}
