/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trabajador;

import Autor.BuscarAutor;
import Conexion.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class BuscarTrabajador extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarTrabajador
     */
    public BuscarTrabajador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mipanel = new javax.swing.JPanel();
        lblrut = new javax.swing.JLabel();
        txtrut = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        lblnombre = new javax.swing.JLabel();
        lblcontrato = new javax.swing.JLabel();
        lblfechadenacimiento = new javax.swing.JLabel();
        lblcorreo = new javax.swing.JLabel();
        lbltelefono = new javax.swing.JLabel();
        lbldireccion = new javax.swing.JLabel();
        lblapellidopaterno = new javax.swing.JLabel();
        lblapellidomaterno = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lblrut.setText("Rut");

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        lblnombre.setText("Nombre :");

        lblcontrato.setText("Fecha  Contrato Laboral :");

        lblfechadenacimiento.setText("Fecha de Nacimiento :");

        lblcorreo.setText("Correo :");

        lbltelefono.setText("Telefono :");

        lbldireccion.setText("Direcion :");

        lblapellidopaterno.setText("Apellido Paterno :");

        lblapellidomaterno.setText("Apellido Materno :");

        javax.swing.GroupLayout MipanelLayout = new javax.swing.GroupLayout(Mipanel);
        Mipanel.setLayout(MipanelLayout);
        MipanelLayout.setHorizontalGroup(
            MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MipanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblnombre, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblapellidopaterno, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblcorreo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbldireccion, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblfechadenacimiento, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblcontrato, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbltelefono, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(MipanelLayout.createSequentialGroup()
                        .addComponent(lblapellidomaterno)
                        .addGap(33, 33, 33)))
                .addGap(21, 234, Short.MAX_VALUE))
            .addGroup(MipanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblrut)
                .addGap(31, 31, 31)
                .addComponent(txtrut, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        MipanelLayout.setVerticalGroup(
            MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MipanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar)
                    .addComponent(lblrut))
                .addGap(31, 31, 31)
                .addComponent(lblnombre)
                .addGap(18, 18, 18)
                .addComponent(lblapellidopaterno)
                .addGap(18, 18, 18)
                .addComponent(lblapellidomaterno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(lbldireccion)
                .addGap(18, 18, 18)
                .addComponent(lbltelefono)
                .addGap(18, 18, 18)
                .addComponent(lblcorreo)
                .addGap(18, 18, 18)
                .addComponent(lblfechadenacimiento)
                .addGap(18, 18, 18)
                .addComponent(lblcontrato)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mipanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Mipanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        try {                                          
            Conexion ObjetoConexion = new Conexion();
            
            String rut = txtrut.getText();
            if (rut.trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Complete el espacio en blanco"); 
            }
            
            String query = "Select * from cliente where rut = '"+rut+"'";
            
            state = ObjetoConexion.getCon().createStatement();
            
            res = state.executeQuery(query);
            
            if (res.next()) {
                lblnombre.setText("Nombre:" + res.getString("Nombre"));
                lblapellidopaterno.setText("Apellido Materno :" + res.getString("Apellido Paterno"));
                lblapellidomaterno.setText("Apellido Paterno :" + res.getString("Apellido Materno"));
                lbldireccion.setText("Direccion :" + res.getString("Direcion"));
                lbltelefono.setText("Telefono :" + res.getString("Telefono"));
                lblcorreo.setText("Correo :" + res.getString("Correo"));
                lblfechadenacimiento.setText("Fecha de Nacimiento :" + res.getString("Fecha de Nacimiento"));
                lblcontrato.setText("Fecha Contrato Laboral :" + res.getString("Fecha Contrato Laboral"));
            }
            else{
                JOptionPane.showMessageDialog(this, "No hay Registro");
                txtrut.setText("");
                lblnombre.setText("Nombre:");
                lblapellidopaterno.setText("Apellido Paterno:");
                lblapellidomaterno.setText("Apellido Materno:");
                lbldireccion.setText("Direccion");
                lbltelefono.setText("Telefono");
                lblcorreo.setText("Correo");
                lblfechadenacimiento.setText("Fecha de Nacimiento");
                lblcontrato.setText("Fecha Contrato Laboral");

            }
        }
        catch (SQLException ex) {
            Logger.getLogger(BuscarAutor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    ResultSet res;
    Statement state;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Mipanel;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JLabel lblapellidomaterno;
    private javax.swing.JLabel lblapellidopaterno;
    private javax.swing.JLabel lblcontrato;
    private javax.swing.JLabel lblcorreo;
    private javax.swing.JLabel lbldireccion;
    private javax.swing.JLabel lblfechadenacimiento;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblrut;
    private javax.swing.JLabel lbltelefono;
    private javax.swing.JTextField txtrut;
    // End of variables declaration//GEN-END:variables
}
