/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trabajador;

import Cliente.CrearCliente;
import Conexion.Conexion;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class CrearTrabajador extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistrarTrabajador
     */
    public CrearTrabajador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mipanel = new javax.swing.JPanel();
        lblrut = new javax.swing.JLabel();
        txtrut = new javax.swing.JTextField();
        lblnombre = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        lblapellidoma = new javax.swing.JLabel();
        txtapellidomaterno = new javax.swing.JTextField();
        lblapellidopa = new javax.swing.JLabel();
        txtapellidopaterno = new javax.swing.JTextField();
        lblDireecion = new javax.swing.JLabel();
        txtdirrecion = new javax.swing.JTextField();
        lbltelefono = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        lblcorreo = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        lblfechadenacimiento = new javax.swing.JLabel();
        txtfechadenacimiento = new javax.swing.JTextField();
        lblcontrato = new javax.swing.JLabel();
        txtcontrato = new javax.swing.JTextField();
        btncrear = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lblrut.setText("Rut");

        lblnombre.setText("Nombre");

        lblapellidoma.setText("Apellido Materno");

        lblapellidopa.setText("Apellido Paterno");

        lblDireecion.setText("Direcion");

        lbltelefono.setText("Telefono");

        lblcorreo.setText("Correo");

        lblfechadenacimiento.setText("Fecha de Nacimiento");

        lblcontrato.setText("Fecha contrato Laboral");

        btncrear.setText("Crear");
        btncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MipanelLayout = new javax.swing.GroupLayout(Mipanel);
        Mipanel.setLayout(MipanelLayout);
        MipanelLayout.setHorizontalGroup(
            MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MipanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MipanelLayout.createSequentialGroup()
                        .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnombre)
                            .addComponent(lblrut)
                            .addComponent(lblapellidopa)
                            .addComponent(lblcorreo)
                            .addComponent(lbltelefono)
                            .addComponent(lblDireecion)
                            .addComponent(lblfechadenacimiento)
                            .addComponent(lblapellidoma)
                            .addComponent(lblcontrato))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfechadenacimiento)
                            .addComponent(txtdirrecion)
                            .addComponent(txtapellidopaterno)
                            .addComponent(txtapellidomaterno)
                            .addComponent(txtrut)
                            .addComponent(txtnombre)
                            .addComponent(txttelefono)
                            .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcontrato)))
                    .addGroup(MipanelLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btncrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );
        MipanelLayout.setVerticalGroup(
            MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MipanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblrut)
                    .addComponent(txtrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombre)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblapellidoma)
                    .addComponent(txtapellidomaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtapellidopaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblapellidopa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdirrecion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDireecion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltelefono)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfechadenacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblfechadenacimiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcontrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcontrato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btncrear)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mipanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mipanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearActionPerformed
        try {                                             
            
            Conexion ObjetoConexion = new Conexion();
            
            String nombre = txtnombre.getText();
            String apellidopaterno = txtapellidopaterno.getText();
            String apellidomaterno = txtapellidomaterno.getText();
            String direccion = txtdirrecion.getText();
            String telefono = txttelefono.getText();
            String correo = txtcorreo.getText();
            String fechadenacimineto = txtfechadenacimiento.getText();
            String fechacontratolaboral = txtfechadenacimiento.getText();


                 
            if (nombre.trim().equals("")|| apellidomaterno.trim().equals("")|| apellidopaterno.trim().equals("")|| direccion.trim().equals("")|| telefono.trim().equals("")|| correo.trim().equals("")|| fechadenacimineto.trim().equals("")||fechacontratolaboral.trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Complete los espacios en blanco");
            }
        try{

            String query = " insert into trabajador values ('"+nombre+"','"+apellidomaterno+"','"+apellidopaterno+"','"+direccion+"','"+telefono+"','"+correo+"','"+fechadenacimineto+"','"+fechacontratolaboral+"')";

            state = ObjetoConexion.getCon().createStatement();

            try{
            int x = state.executeUpdate(query);

            if (x > 0) {
                JOptionPane.showMessageDialog(this, "Registrado Correctamente");
            }
            else{
                JOptionPane.showMessageDialog(this, "No se pudo Registrar");
              }
            }
            catch(SQLException error){
                JOptionPane.showMessageDialog(this, "Rut ya registrado");
            }

            }
        catch(NumberFormatException error){
        }


        } catch (SQLException ex) {
        Logger.getLogger(CrearTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btncrearActionPerformed

    Statement state;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Mipanel;
    private javax.swing.JButton btncrear;
    private javax.swing.JLabel lblDireecion;
    private javax.swing.JLabel lblapellidoma;
    private javax.swing.JLabel lblapellidopa;
    private javax.swing.JLabel lblcontrato;
    private javax.swing.JLabel lblcorreo;
    private javax.swing.JLabel lblfechadenacimiento;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblrut;
    private javax.swing.JLabel lbltelefono;
    private javax.swing.JTextField txtapellidomaterno;
    private javax.swing.JTextField txtapellidopaterno;
    private javax.swing.JTextField txtcontrato;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdirrecion;
    private javax.swing.JTextField txtfechadenacimiento;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtrut;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
